SELECT
    f.*,
    d.DAT_REF_FORMATADA,
    p.DSC_EMPRESA,
    p.COD_PRACA,
    p.DSC_PRACA,
    p.DSC_SENTIDO,
    p.COD_VIA
FROM DW.FAT_ARRECADACAO_TRAFEGO f

LEFT JOIN DW.DIM_DAT_PERIODO d
    ON f.SK_DAT_PERIODO = d.SK_DAT_PERIODO

LEFT JOIN DW.DIM_EMPRESA_PRACA_VIA p
    ON f.SK_EMPRESA_PRACA_VIA = p.SK_EMPRESA_PRACA_VIA
WHERE p.DSC_EMPRESA = 'NASCENTES DAS GERAIS'








