[oracle]
DB_HOST    = "10.254.255.82"
DB_PORT    = 1521
DB_SERVICE = "srv_bi"
DB_USER    = "CONSULTABI"
DB_PASSWORD = "C0nsult4DW!#2025"
SK_EMPRESA = 6

[sqlserver]
SQL_HOST = "192.168.40.22"
SQL_PORT = 1433
SQL_DB   = "AT3_db_2"
SQL_USER = "sa"
SQL_PASS = "$4dmp4dr40@nasc"
